### ISSUE TITLE
新增忘記密碼與重設密碼功能

### ISSUE THREAD

**Issue by s35241607** [s35241607/lan-side-project#24]
**Description**:
為了提升使用者體驗，我們需要實作「忘記密碼」功能，包括以下步驟：

1. 使用者在登入頁面上點擊「忘記密碼」。
2. 使用者輸入註冊的電子郵件，並發送重設密碼的郵件。
3. 使用者點擊郵件中的連結後，會被導向到重設密碼頁面。
4. 使用者在重設密碼頁面輸入新密碼並提交。

**Tasks**:
- [ ] 設計並實作「忘記密碼」頁面，讓使用者可以輸入電子郵件。
- [ ] 設計並實作「重設密碼」頁面，讓使用者輸入新密碼。
- [ ] 在「忘記密碼」頁面成功送出後，顯示一個提示，告知使用者已經發送重設密碼的郵件。
- [ ] 當使用者成功重設密碼後，導向登入頁面，並顯示成功訊息。

**Acceptance Criteria**:
1. 使用者可以順利進入忘記密碼頁面並輸入電子郵件。
2. 在重設密碼頁面，使用者可以順利輸入並提交新密碼。
3. 密碼重設成功後，使用者將被引導回登入頁面。

**Additional Context**:
- 請與後端協調以確保重設密碼的 API 正確實作並處理驗證。
- 重設密碼的郵件內容需要清晰，並且包含有效的連結，並附有到期時間的提示。

**Comment by s35241607** [comment]
信件會回傳這個 path reset-password?userId={user.Id}&token={token}
userId 跟 token 回傳

**Comment by s35241607** [comment]
寄信部分自己要在 backend 的 .env 新增 STMP
可以去 google 設定自己的
https://www.ibest.com.tw/news-detail/gmail-smtp/

**Comment by ChiuZhenHuang** [comment]
信箱的內容導向網址是
http://localhost:5173/reset-password
你打5713錯ㄌ
阿為啥userId 跟 token 回傳是在信箱內容裡 不是在response

**Comment by s35241607** [comment]
阿你要自己改阿，我哪知道你 port 掛哪個 凸

然後 userId 跟 token 要記到信箱才能直接點網址過去阿
不然 response 就直接丟給使用者了，沒辦法做到雙因子驗證
